--- 
 - name: "Windows | Override architecture if 64-bit"
   set_fact:
     windows_arch: 64
   when:
     - ansible_architecture == "64-bit"

 - name: "Windows | Set path to zabbix.exe"
   set_fact:
     zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\win{{ windows_arch }}\zabbix_agentd.exe'

 - name: "Windows | Set variables specific to Zabbix 5.0"
   set_fact:
     zabbix_win_package: zabbix_agent-{{ zabbix_version_long }}-windows-amd64.zip
     zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agentd.exe'
   when:
     - zabbix_version_long is version('5.0.0', '>=')

 - name: "Windows | Create directory structure"
   win_file:
     path: "{{ item }}"
     state: directory
   with_items:
     - "{{ zabbix_win_install_dir }}"

 - name: "Windows | Download Zabbix Agent Zip file"
   win_get_url:
     url: "{{ zabbix_win_download_link }}"
     dest: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
     force: False
     follow_redirects: all
     proxy_url: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
   register: zabbix_agent_win_download_zip
   until: zabbix_agent_win_download_zip is succeeded

 - name: "Windows | Unzip file"
   win_unzip:
     src: '{{ zabbix_win_install_dir }}\{{ zabbix_win_package }}'
     dest: "{{ zabbix_win_install_dir }}"
     creates: '{{ zabbix_win_exe_path }}'

 - name: "Windows | Configure zabbix-agent"
   win_template:
     src: zabbix_agentd.conf.j2
     dest: '{{ zabbix_win_install_dir }}\zabbix_agentd.conf'
   notify: restart win zabbix agent

 - name: Create a new service
   win_service:
     name: Zabbix Agent
     path: '{{ zabbix_win_exe_path }} --config {{ zabbix_win_install_dir }}\zabbix_agentd.conf'

 - name: "Windows | Set service startup mode to auto and ensure it is started"
   win_service:
     name: Zabbix Agent
     start_mode: auto
     state: started

